pdsrooz:
  # Publish all joint states ---------------------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers -------------------------------------------------------
  case_to_axis_position_controller:
    type: effort_controllers/JointEffortController
    joint: case_to_axis
    #pid: {p: 1.0, i: 0.0, d: 0.0}
  axis_to_rod_position_controller:
    type: effort_controllers/JointPositionController
    joint: axis_to_rod
    pid: {p: 1.7, i: 1.74, d: 0.01}
